
[tools]
java = "openjdk-17"
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist

_.file = ".env.yaml"
PYTHONPATH = "."

[hooks]
enter = "echo 'Welcome to the template project'"
